# Generated by Django 5.0 on 2023-12-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='data',
            field=models.CharField(max_length=255, verbose_name='Дата'),
        ),
    ]
