# Generated by Django 5.0 on 2023-12-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_pagecontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='pagecontact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема'),
        ),
    ]
