# Generated by Django 5.0 on 2023-12-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_pagecontact_message_alter_pagecontact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontact',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontact',
            name='message',
            field=models.TextField(default=1, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontact',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
