# Generated by Django 5.0 on 2023-12-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_pagecontact_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontact',
            name='text',
        ),
    ]
