# Generated by Django 5.0 on 2023-12-25 17:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionInlineInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фотографии')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_inline', to='secondary.condition')),
            ],
            options={
                'unique_together': {('place_info', 'image')},
            },
        ),
    ]
