# Generated by Django 5.0 on 2023-12-26 04:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название_услуги')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание_услуги')),
                ('image', models.ImageField(upload_to='image_usluga', verbose_name='Фотграфия_услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Условие ', 'verbose_name_plural': 'Условия'},
        ),
    ]
