# Generated by Django 5.0 on 2023-12-26 04:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя_боса')),
                ('image_boss', models.ImageField(upload_to='image_boss/', verbose_name='Фото боса')),
                ('about_boss', ckeditor.fields.RichTextField(verbose_name='Информация про боса')),
            ],
            options={
                'verbose_name': 'Босс',
                'verbose_name_plural': 'Босс',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='about_boss',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image_boss',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
