# Generated by Django 5.0 on 2023-12-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_teamabout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamabout',
            options={'verbose_name': 'Член команды', 'verbose_name_plural': 'Члены команды'},
        ),
    ]
