# Generated by Django 5.0 on 2023-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(default=1, upload_to='image', verbose_name='Фото Граунд'),
            preserve_default=False,
        ),
    ]
