# Generated by Django 5.0 on 2023-12-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPluse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_gallery', verbose_name='Фотография')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='secondary.gallery')),
            ],
            options={
                'unique_together': {('place_info', 'image')},
            },
        ),
    ]
