# Generated by Django 5.0 on 2023-12-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_gallerypluse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypluse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_gallery', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='gallerypluse',
            name='place_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='secondary.gallery'),
        ),
    ]
