# Generated by Django 5.0 on 2023-12-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0012_alter_gallerypluse_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPluse',
        ),
    ]
