# Generated by Django 5.0 on 2023-12-27 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0016_news_descriptions2'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='descriptions1',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='descriptions2',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='letter',
            field=models.TextField(default=1, verbose_name='Письмо текст'),
            preserve_default=False,
        ),
    ]
