# Generated by Django 5.0 on 2023-12-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0017_team_descriptions1_team_descriptions2_team_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='descriptions1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='descriptions2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='letter',
        ),
    ]
