# Generated by Django 5.0 on 2023-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_remove_team_descriptions1_remove_team_descriptions2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamabout',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='teamabout',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Инстаграм'),
        ),
        migrations.AlterField(
            model_name='teamabout',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='twitter'),
        ),
    ]
