# Generated by Django 5.0 on 2023-12-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_settings_descriptions_settings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='facebook',
            field=models.URLField(default=1, verbose_name='Фейсбук'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Инстаграм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='locations',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='telegram',
            field=models.URLField(default=1, verbose_name='Телеграм'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp',
            field=models.URLField(default=1, verbose_name='Вотсап'),
            preserve_default=False,
        ),
    ]
