# Generated by Django 5.0 on 2023-12-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_settings_email_settings_facebook_settings_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='whatsapp',
            new_name='twitter',
        ),
    ]
