# Generated by Django 5.0 on 2023-12-25 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_slide_remove_settings_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=ckeditor.fields.RichTextField(verbose_name='Название'),
        ),
    ]
