# Generated by Django 5.0 on 2023-12-26 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_slide_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_title', to='base.settings')),
            ],
            options={
                'unique_together': {('settings', 'phone')},
            },
        ),
    ]
